version: '3.5'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $PUID:$PGID
    # network_mode: 'host'      # Uncomment this line if you want to use host network
    ports:
      - 8096:8096
    volumes:
      - ${USERDIR}/jellyfin/config:/config
      - ${USERDIR}/jellyfin/cache:/cache
      - ${USERDIR}/jellyfin/media:/media
    environment:
      - JELLYFIN_PublishedServerUrl="stream.${DOMAINNAME_CLOUD_SERVER}"
    restart: 'unless-stopped'

  # TransmissionBT - Torrent VPN Downloader
  transmission-vpn:
    image: haugene/transmission-openvpn:latest
    container_name: transmission-vpn
    ports:
      - "$PORT_TRANS:9091"
    cap_add:
      - NET_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/transmission/appdata/transmission-vpn/data:/data
      - ${USERDIR}/transmission/appdata/transmission-vpn/config:/config
      - ${USERDIR}/downloads:/data/downloads
    environment:
      USER_ID: $PUID
      GROUP_ID: $PGID
      TZ: $TZ
      OPENVPN_PROVIDER: NORDVPN
      OPENVPN_USERNAME: ${NORD_USERNAME}
      OPENVPN_PASSWORD: ${NORD_PASSWORD}
      NORDVPN_COUNTRY: BR
      NORDVPN_PROTOCOL: tcp
      NORDVPN_CATEGORY: legacy_p2p
      LOCAL_NETWORK: "${LOCAL_NETWORK}"
      UMASK_SET: 2
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_RPC_HOST_WHITELIST: "127.0.0.1,${SERVER_IP}"
      TRANSMISSION_RPC_PASSWORD: ${TRANSMISSION_RPC_PASSWORD}
      TRANSMISSION_RPC_USERNAME: ${TRANSMISSION_RPC_USERNAME}
      TRANSMISSION_UMASK: 2
      TRANSMISSION_RATIO_LIMIT: 1.0
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_ALT_SPEED_DOWN: 2000
      TRANSMISSION_ALT_SPEED_ENABLED: "false"
      TRANSMISSION_ALT_SPEED_UP: 100
      TRANSMISSION_SPEED_LIMIT_DOWN: 10000
      TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
      TRANSMISSION_SPEED_LIMIT_UP: 500
      TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"
      TRANSMISSION_INCOMPLETE_DIR: /data/downloads/torrents/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
      TRANSMISSION_WATCH_DIR: /data/downloads/torrents
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /data/downloads/torrents
      LOG_TO_STDOUT: "true"